### ISSUE TITLE
Request path encoding error on Windows OS

### ISSUE THREAD

**Issue by kuscuogluo** [Dmitrii-I/sportmonks#8] opened 2020-01-13 07:16 UTC
Initializer function throws a 404 error and when compared with a Mac OS machine, the only difference in the request path. Hence, the library does not work at all.

On Windows:
'/api/v2.0%5Ccontinents?api_token=<token>&tz=Europe%2FIstanbul'
On Mac:
'/api/v2.0/continents?api_token=<token>&tz=Europe%2FIstanbul'

**Comment by burakuyar** [comment] 2020-01-13 07:30
The reason look like the os.path library, which uses the OS's seperator character for path joins.

https://stackoverflow.com/questions/50585275/can-i-join-urls-using-os-path-join-in-python-or-is-there-a-better-way

**Comment by burakuyar** [comment] 2020-01-13 07:42
Using "/".join(<list_of_items_to_be_joined>) instead of os.path.join will probably solve the problem.

**Comment by Dmitrii-I** [comment] 2020-01-13 19:52
My bad, this seems like a bug. Will try to fix ASAP and release.

**Comment by Dmitrii-I** [comment] 2020-01-14 21:03
To solve this properly I need to first reproduce the bug. I am pretty sure if I run unit tests in Windows, the bug will appear. Problem is that the unit tests do not run on Windows as part of CI but only on Linux.

I will first migrate the CI from Travis (Linux only) to GitHub Actions (Linux, Windows, and macOS). 

Once we're on GitHub Actions, the bug should cause the CI to fail on Windows runner. I will then fix the bug and publish to PyPI.

**Comment by Dmitrii-I** [comment] 2020-02-03 08:07
The bug has been fixed in version 1.1.1 which is now on PyPI: https://pypi.org/project/sportmonks/1.1.1/

It took a bit longer because I wanted to setup GitHub Actions tests on Windows. This is done and now the tests will run on Ubuntu and Windows on every push.

**Closed by Dmitrii-I** 2020-02-03 08:07 UTC
Labels: bug
